services:
  - type: web
    name: personal-website
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet PersonalWebsite.dll
    buildFilter:
      paths:
        - "**/*"
    plan: free