services:
  - type: web
    name: personalwebsite
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/PersonalWebsite.dll
    buildFilter:
      paths:
        - "**/*"
    plan: free